name: SKY UX CI

on:
  pull_request:
    branches:
      - master
      - 3.x.x
      - 5.0.0-next
  push:
    branches:
      - master
      - 3.x.x
      - 5.0.0-next
    tags:
      - '*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.18.x'
      - uses: blackbaud/skyux-sdk-actions@ng-14
        with:
          code-coverage-browser-set: speedy
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          project: stache
          npm-token: ${{ secrets.NPM_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
